### ISSUE TITLE
add reference(s) for databases

### ISSUE THREAD

**Issue by capsulecorplab** [LearnTeachCode/baldwinpark-code-and-coffee#16]
- [x] database design patterns (i.e., relational vs. non-relational) and pros/cons on competing implementations
- [x] interactive learning tutorials for building databases

**Comment by sugarsyntax** [comment]
Going to vet these resources: https://academy.vertabelo.com/blog/18-best-online-resources-for-learning-sql-and-database-concepts/

Leaving it here for future reference.

**Comment by capsulecorplab** [comment]
Amidst editing/rephrasing the description, I suspect this issue might already be closed via the [system-design](https://github.com/LearnTeachCode/baldwinpark-code-and-coffee#system-design) and PostgreSQL resources, but open to second opinions.

**Comment by cynful** [comment]
I'd close the issue, but then open another focused more on an enhancement.
Different types of dbs and why article or code examples.
